### ISSUE TITLE
Change restheart password within docker

### ISSUE THREAD

**Issue by MyWay** [SoftInstigate/restheart-docker#10]
How can I change restheart's password ("changeit") using it with the docker image?

**Comment by ujibang** [comment]
Restheart docker container is configured to use the _SimpleFileIdentityManager_: with this Identity Manager the users are specified in the security.yml configuration file, so you need to change this file in the docker container.

(you might want to try _DbIdentityManager_ with userbase defined by a mongodb collection).

to use a custom security.yml conf file (with your users/password) you [can mount your security.yml from your Docker engine’s host into a container](https://docs.docker.com/engine/tutorials/dockervolumes/).

if conf file is in the host dir `/path/to/security.yml`

```
docker run --rm -i -t -p 80:8080 -v /path/to/security.yml:/opt/restheart/etc/security.yml:ro --name restheart --link mongodb:mongodb softinstigate/restheart:3.0.0
```

**Comment by MyWay** [comment]
Thank you very much.
