### ISSUE TITLE
Failed to execute docker run --rm -i -t -p 80:8080 --name restheart --link mongodb softinstigate/restheart

### ISSUE THREAD

**Issue by mrodfuentes** [SoftInstigate/restheart-docker#7]
Failed to execute:
SO: Lubuntu 15.10
docker run --rm -i -t -p 80:8080 --name restheart --link mongodb softinstigate/restheart
this is the error:
invalid value "mongodb" for flag --link: Invalid format to parse.  mongodb should match template name:alias
Thanks!!

**Comment by mkjsix** [comment]
Did you start the mongodb container first? Which version of docker are you running?

**Comment by mkjsix** [comment]
I really think you are running a too old docker version, please check it with `docker -v`

**Comment by mrodfuentes** [comment]
Hi Maurizio
My docker version is 1.6.2.
Regards
Miguel Rodríguez

2016-04-21 18:15 GMT+02:00 Maurizio Turatti <notifications@github.com>:

> I really think you are running a too old docker version, please check it
> with docker -v
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/SoftInstigate/restheart-docker/issues/7#issuecomment-212991293>
>



-- 
Miguel Rodríguez

**Comment by mrodfuentes** [comment]
I have updated docker version to 1.11 and now it works.
Thanks
