### ISSUE TITLE
Proposal: remove the "latest" tag from public images at Docker hub

### ISSUE THREAD

**Issue by mkjsix** [SoftInstigate/restheart-docker#8]
Automated Build repositories still don't allow to properly manage the latest tag on images. These are the problems:
1. need to handle the `latest` tag manually, by triggering two separate builds when a new release of RESTHeart is available
2. `latest` is not just a tag, it's actually a separate image, which is really bad (at present `latest` == 2.0.2 but they have different image IDs, while they must be the same)
3. the concept of `latest` itself is inconsistent, because it means different things to different people
4. when running a docker image, especially in production, the tag should always be set explicitly

For the above reasons I see little use for this tag and we should opt to remove the `latest` tag from the repo and move to a fully automated build, triggered by `git push`.

I'd like to hear opinions asap about this. If there aren't strong reasons against, I'll remove the tag promptly.

/CC @ujibang @RickyGeek

**Comment by ujibang** [comment]
closing for low activity
